### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by xVoldx** [anidl/crunchyroll-downloader-nx#28]
=== Crunchyroll Downloader NX 4.21.0-beta.2 ===

/content/crunchyroll-downloader-nx/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/content/crunchyroll-downloader-nx/node_modules/got/dist/source/index.js:14:18)

**Comment by anidl** [comment]
what node version u use?

**Comment by xVoldx** [comment]
v8.11.3

**Comment by anidl** [comment]
its outdated, update to v12

**Comment by xVoldx** [comment]
Thank you already updated it when u asked me about the version and it working right now thanks again 😄
