### ISSUE TITLE
Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by vicentehenrique1998** [anidl/crunchyroll-downloader-nx#31]
How to fix this?

=== Crunchyroll Downloader NX 4.22.0 ===

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'yargs'
Require stack:
- C:\crunchyroll-downloader-nx-4.22.0-win64\modules\module.app-args.js
- C:\crunchyroll-downloader-nx-4.22.0-win64\crunchy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\crunchyroll-downloader-nx-4.22.0-win64\modules\module.app-args.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\crunchyroll-downloader-nx-4.22.0-win64\\modules\\module.app-args.js',
    'C:\\crunchyroll-downloader-nx-4.22.0-win64\\crunchy.js'
  ]
}

**Comment by anidl** [comment]
fixed in 4.22.1
