### ISSUE TITLE
[BUG] TypeError: Intl.DisplayNames is not a constructor

### ISSUE THREAD

**Issue by Pfuenzle** [anidl/crunchyroll-downloader-nx#36]
** Main info: **
I tried to run it with --help and get following error.
This also happens when trying to download anything or with any other command I tried

Script version: 4.23.1
Show ID: none, --help
Episode ID: 

** Additional Info: **
Error:
=== Crunchyroll Downloader NX 4.23.1 ===

/output/modules/module.langsData.js:19
    const getLangName = new Intl.DisplayNames(['en'], {type: 'language'});
                        ^

TypeError: Intl.DisplayNames is not a constructor
    at /output/modules/module.langsData.js:19:25
    at Object.<anonymous> (/output/modules/module.langsData.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/output/crunchy.js:24:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by bobbers0n** [comment]
Have node.js 14+ downloaded.
