### ISSUE TITLE
[BUG] Unable to download

### ISSUE THREAD

**Issue by Oujiii** [anidl/crunchyroll-downloader-nx#46]
**Main info:**
Unable to download at all, not sure what else to do. I tried with other series as well.

Script version: 4.23.1
Show ID: 21055
Episode ID: 623251

**Additional Info:**

```
$:~/crunchy# node crunchy -s 21055 -e 1

=== Crunchyroll Downloader NX 4.23.1 ===

[S:21055] Attack on Titan 
  [0025|642211] 25 - The Wall - Raid on Stohess District (3)
   - FreePubDate: 2013-10-05 20:15:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0024|642209] 24 - Mercy - Raid on Stohess District (2)
   - FreePubDate: 2013-09-28 22:30:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0023|642207] 23 - Smile - Raid on Stohess District (1)
   - FreePubDate: 2013-09-21 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0022|642205] 22 - The Defeated - 57th Expedition Beyond the Walls (6)
   - FreePubDate: 2013-09-14 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0021|642203] 21 - Crushing Blow - 57th Expedition Beyond the Walls (5)
   - FreePubDate: 2013-09-07 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0020|642201] 20 - Erwin Smith - 57th Expedition Beyond the Walls (4)
   - FreePubDate: 2013-08-31 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0019|642199] 19 - Bite - 57th Expedition Beyond the Walls (3)
   - FreePubDate: 2013-08-24 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0018|642197] 18 - Forest of Giant Trees - 57th Expedition Beyond the Walls (2)
   - FreePubDate: 2013-08-17 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0017|642195] 17 - Female Titan - 57th Expedition Beyond the Walls (1)
   - FreePubDate: 2013-08-10 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0016|642193] 16 - What Should Be Done - Night Before the Counteroffensive (3)
   - FreePubDate: 2013-08-03 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0015|642191] 15 - Special Ops Squad - Night Before the Counteroffensive (2)
   - FreePubDate: 2013-07-27 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0014|642189] 14 - Still Can't See - Night Before the Counteroffensive (1)
   - FreePubDate: 2013-07-20 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [S001|639475] 13.5 - Since That Day
   - FreePubDate: 2013-07-13 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME
  [0013|623915] 13 - Primal Desires - The Battle for Trost (9)
   - FreePubDate: 2013-07-06 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0012|623913] 12 - Wound - The Battle for Trost (8)
   - FreePubDate: 2013-06-29 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0011|623911] 11 - Icon - The Battle for Trost (7)
   - FreePubDate: 2013-06-22 18:30:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0010|623909] 10 - Response - The Battle for Trost (6)
   - FreePubDate: 2013-06-15 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0009|623907] 9 - Where the Left Arm Went - The Battle for Trost (5)
   - FreePubDate: 2013-06-08 23:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0008|623905] 8 - Hearing the Heartbeat - The Battle for Trost (4)
   - FreePubDate: 2013-06-02 01:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0007|623903] 7 - The Small Blade - The Battle for Trost (3)
   - FreePubDate: 2013-05-26 15:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0006|623901] 6 - The World the Girl Saw - Battle for Trost (2)
   - FreePubDate: 2013-05-19 15:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0005|623899] 5 - First Battle - Battle of Trost (1)
   - FreePubDate: 2013-05-12 15:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0004|623257] 4 - Night of the Graduation Ceremony - Humanity Rises Again (2)
   - FreePubDate: 2013-05-05 15:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0003|623255] 3 - A Dim Light in the Darkness of Despair - Humanity Rises Again (1)
   - FreePubDate: 2013-04-28 19:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0002|623253] 2 - That Day - The Fall of Zhiganshina (2)
   - FreePubDate: 2013-04-21 19:00:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [0001|623251] 1 - To You, 2,000 Years in the Future -The Fall of Zhiganshina (1)
   - FreePubDate: 2013-04-14 19:15:00 UTC
   - Subtitles: enUS, esLA, ptBR, arME, ruRU
  [S002|623365] PV
   - FreePubDate: 2013-04-18 00:32:21 UTC

[INFO] Selected Episodes: 0001

Requesting: [623251] Attack on Titan - 1 - To You, 2,000 Years in the Future -The Fall of Zhiganshina (1)
/root/crunchy/crunchy.js:587
    const contextJson = JSON.parse(contextData[1]);
                                              ^

TypeError: Cannot read property '1' of null
    at getMedia (/root/crunchy/crunchy.js:587:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getShowById (/root/crunchy/crunchy.js:530:13)
    at async /root/crunchy/crunchy.js:111:9
```

**Comment by bgette** [comment]
try -e m623251

**Comment by Oujiii** [comment]
Thank you, but it didn't work.

**Comment by bgette** [comment]
if you reauth?

**Comment by Oujiii** [comment]
Tried that too, not sure what is going on. Is this script working for you?

**Comment by bgette** [comment]
yep with this version === Crunchyroll Downloader NX 4.22.1 ===

**Comment by Oujiii** [comment]
Hmm, that doesn't work for me either, I get another error.

```
Requesting: [623251] Attack on Titan - 1 - To You, 2,000 Years in the Future -The Fall of Zhiganshina (1)
/root/crunchy/crunchy.js:547
    const eligibleRegion = JSON.parse(contextData[1]).potentialAction
                                                 ^

TypeError: Cannot read property '1' of null
    at getMedia (/root/crunchy/crunchy.js:547:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getShowById (/root/crunchy/crunchy.js:524:13)
    at async /root/crunchy/crunchy.js:109:9
```

This is available in my country, so I know this is not it.

**Comment by bgette** [comment]
npm i ?

**Comment by Oujiii** [comment]
I did that before running (as it is required to install it).

**Comment by RichardArc** [comment]
I just started getting the same issue but it seems to only happen when I'm authenticated. If I delete the session.yml it gets past the issue. Though you cant download the latest episodes. Tried with exe for 4.23.1 (and a couple other versions) and just using node with the latest code

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
